# Site settings
title: Light of Atan Campaign Setting
email:
author:
description:
url:

category-list: [ General, Rules, Nations, Races, Locations, History, Pantheons, Organizations ]

# Build settings
permalink: :title/
